config/routes.rb
Rails.application.routes.draw do
  resources :home
  get '/about' => 'about#top'
  get '/provider' => 'about#provider'
  get '/cashback' => 'about#cashback'

  get '/select' => 'select#top'
  get '/autoSelection' => 'select#autoSelection'
  get '/docomo' => 'select#docomo'
  get '/softbank' => 'select#softbank'
  get '/au' => 'select#au'
  get '/nuro' => 'select#nuro'
  get '/commufa' => 'select#commufa'
  get '/sonet' => 'select#sonet'
  get '/ocn' => 'select#ocn'
  get '/biglobe' => 'select#biglobe'
  get '/unext' => 'select#unext'
  post '/result' => 'select#result'
  get '/result' => 'select#autoSelection'
  get '/all' => 'select#all'
  root 'home#top'

end

app/models/hikari.rb
class Hikari < ActiveRecord::Base
  serialize :provider
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def top
  end
  def provider
  end
  def cashback
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/select_controller.rb
class SelectController < ApplicationController
  def top
  end
  def autoSelection
    @provider = ["なし","plala", "So-net", "BIGLOBE","@TCOM", "Yahoo!BB","@nifty",
      "DTI", "excite", "エディオンネット","OCN",
       "SYNAPSE", "楽天", "01光コアラ", "ANDLINE", "＠ネスク", "hi-ho", "GMO",
       "ic-net", "Tigers-net.com", "TikiTiki", "U-Pa!", "AsahiNet",
        "TNC",  "WAKWAK", "＠ちゃんぷるネット","au one net"]
  end

  def result
    @hikaris = Hikari.all
    @rank = autoSelect
    @rank = Hash[@rank.sort_by{ |_, v| -v }]
  end
  def all
    @hikaris = Hikari.all
  end
  def docomo
  end
  def softbank
  end
  def au
  end
  def nuro
  end
  def commufa
  end
  def sonet
  end
  def ocn
  end
  def biglobe
  end
  def unext
  end
  private
    def autoSelect
      d = params[:numberOfDocomo].to_i
      s = params[:numberOfSoftBank].to_i
      a = params[:numberOfAu].to_i
      y = params[:numberOfYmobile].to_i
      sim = params[:numberOfSIM].to_i
      if params[:fletsOrNot] == "加入中" then
        flets = 1
      else
        flets = 0
      end

      if params[:tvOrNot] == "利用する" then
        tv = 1
      else
        tv = 0
      end

      rank = {}
      for n in 1..9 do
        count = 0

        @hikari = Hikari.find(n)

        if @hikari.docomo then
          count = count + d * 2
        end
        if @hikari.softbank then
          if params[:telOrNot] == "利用する" then
            count = count + s * 2
          end
        end
        if @hikari.au then
          if params[:telOrNot] == "利用する" then
            count = count + a * 2
          end
        end
        if @hikari.ymobile then
          if params[:telOrNot] == "利用する" then
            count = count + y * 2
          end
        end
        if (@hikari.name == "OCN光") || (@hikari.name == "BIGLOBE光")  then
          count = count + sim
        end
        if @hikari.flets then
          count = count + flets
        end
        if !(@hikari.apartment) then
          if params[:type] == "マンションタイプ" then
            count = count - 1
            if @hikari.path == "nuro" then
              count = count - 1
            end
          end
        end
        if @hikari.tv then
          count = count + tv * 3
        end
        if @hikari.provider.include?(params[:provider]) then
          count = count + 1
        end
        if (@hikari.name == "NURO光") && (params[:area] != "関東") then
          count = -10
        end
        if (@hikari.name == "コミュファ光") && (params[:area] != "中部") then
          count = -10
        end
        count = count + @hikari.priority
        rank[n.to_s] = count
       end
      return rank
     end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/select_helper.rb
module SelectHelper
  
end

app/views/about/cashback.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="about_texts aboutAndProvide">
      <h1> なぜキャッシュバックがもらえる？</h1>
      <h2>代理店</h2>
      <div class="about_text">
        <p>
          インターネット契約や携帯電話の契約は多くの場合代理店が行います。<br>
          街で見かける大手通信事業会社(ドコモ、au、softbankなど)のショップに関しても、
          看板こそ事業会社のものですが、そのほとんどは代理店が運営しています。<br>
          インターネットの契約や申し込みは最近では大手家電量販店でも行うことができるようになりました。<br>
          代理店は顧客と契約を結ぶことで通信事業会社から収入を得ています。<br>
        </p>
      </div>
      <h2>キャッシュバックがもらえる理由</h2>
      <div class="about_text">
        <p>
          基本的に、どこの代理店で契約を結んでも月額料金は変わりません。<br>
          また、通信事業会社が行っている公式キャンペーンも変わらず受けることができます。<br>
          そこで、代理店は価格競争の代わりとして、キャッシュバックや豪華景品プレゼントなど
          独自のキャンペーンを行っています。
        </p>
      </div>
      <h2>ネット上の代理店はキャッシュバックが多い！？</h2>
      <div class="about_text">
        <p>
          これはあくまで傾向ですがインターネット上の代理店はキャッシュバックが高額です。<br>
          また通信事業会社のショップでは公式のキャンペーンのみしか行っていないので、家電量販店やインターネット上の代理店
          を利用した方がお得だといえます。
        </p>
      </div>
      <h2>高額すぎるキャッシュバックに注意！？</h2>
      <div class="about_text">
        <p>
          高額すぎるキャッシュバックはオプションの加入が必須の場合があります。<br>
          500円/月のオプションであっても1年間でみれば12000円ですよね？<br>
          必要なオプションであれば問題ないのですが、キャッシュバック目的の加入には
          注意が必要です。
        </p>
      </div>
      <div class="about_img">
        <%= image_tag "cashback.jpg", :class => "img-responsive center-block"%>
      </div>
      <div class="next text-center">
        <%= link_to(content_tag(:i,'次ページ:「回線を選ぶ」', class: 'glyphicon glyphicon-circle-arrow-right') , select_path ,class: 'btn btn-default')%>
      </div>
    </div>
  </div>
</div>

app/views/about/provider.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="about_texts aboutAndProvide">
      <h1>プロバイダーとは</h1>
      <h2>プロバイダーの役割</h2>
      <div class="about_text">
        <p>
          プロバイダーとは簡単にいえばご自宅の光をインターネットに繋げる事業者のことです。<br>
          少し細かくお話しすると、プロバイダーと契約しIDとパスワードを受け取り、それを使って接続を行うと、
          IPアドレスというものを割り当ててもらうことができます。<br>
          IPアドレスというのはインターネット上の住所のようなものです。<br>
          仮にIPアドレスがない場合、インターネット上のサーバーはあなたの自宅に
          WEBページやWEB上のコンテンツを届けることができません。<br>
        </p>
      </div>

      <h2>光コラボレーション</h2>
      <div class="about_text">
        <p>
          これまでは光回線はNTTフレッツ光、プロバイダーはOCN、ぷらら、BIGLOBEなど別々で契約し、
          請求もバラバラというのが当たり前でした。<br>
          現在では光コラボレーションというのが始まっています。<br>
          光回線をこれまでは<br>
          NTT（フレッツ光） → お客様<br>と提供していましたが、<br>
          光コラボ：NTT → 事業者 → お客様<br>
          と提供していこうというものです。<br>
          詳しくは「回線を選ぶ」の「転用とは」でお話しします。
        </p>
      </div>
      <div class="about_img">
        <%= image_tag "provider.png", :class => "img-responsive center-block"%>
      </div>
      <div class="next text-center">
        <%= link_to(content_tag(:i,'次ページ:「なぜキャッシュバックがもらえる？」', class: 'glyphicon glyphicon-circle-arrow-right') , cashback_path ,class: 'btn btn-default')%>
      </div>
    </div>
  </div>
</div>

app/views/about/top.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="about_texts aboutAndProvide">
      <h1>そもそも光回線って？</h1>

      <h2>光回線とは</h2>
      <div class="about_text">
        <p>インターネットにつながるためには、まずプロバイダー(次章で説明)までつながる必要があります。<br>
          　スマートフォンなどは4G回線などで無線で接続されていますが、ご自宅で利用する場合は安定した有線接続が
            おすすめです。<br>
            ここでの有線とはご自宅までの話で、
            無線LANルーターを利用すれば、Wi-Fi無線の環境を作ることも可能です。<br>
            また、現在スマートフォンなどの通信は通信量の制限が課せられている場合が多く、
            動画の視聴やアプリのダウンロード、アップデートなどが困難な状態です。<br>
            これらのことが通信量の制限がなく高速な光回線が選ばれている理由の１つといえます。<br>
        </p>
      </div>
      <div class="about_img">
        <%= image_tag "net.png", :class => "img-responsive center-block"%>
      </div>
      <h2>光回線のメリットとデメリット</h2>
      <div class="about_text">
        <p>
            光回線は現在のインターネット接続の主流となりつつある回線です。<br>
            それではなぜ、光回線が主流となりつつあるのでしょうか？<br>

            その理由の一つに圧倒的な通信速度があげられます。<br>
            従来利用されてきたCATV(ケーブルテレビ)やADSL(電話回線)と比較すると
            その通信速度はずば抜けています。<br><br>

            しかし、その一方で、料金が高いというデメリットがありました。<br>
            現在ではコラボレーション光の登場などにより光回線の料金はそれほど高くなくなりました。<br>
            また携帯電話の割引などを受けることにより、CATV、ADSLと比較してもより安い料金で利用することも可能に
            なっています。<br>
          </p>
        </div>
        <div class="about_img">
          <%= image_tag "speed.png", :class => "img-responsive center-block"%>
        <div class="about_img">
        <div class="next text-center">
          <%= link_to(content_tag(:i,'次ページ:「プロバイダーとは」', class: 'glyphicon glyphicon-circle-arrow-right') , provider_path ,class: 'btn btn-default')%>
        </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
  <!-- Wrapper for slides -->
<div class="top_main">
    <h3>自宅でネットを始めるなら</h3>
    <h1>ひかりABCで簡単に回線検索。</h1>
    <%= image_tag "plug.png",:class => "center-block main-icon" %>
    <p>あなたの環境を入力するだけで最適な光回線を見つけられます。</p>
</div>


<div class="row">
  <div class="col-md-12">
    <%= image_tag "main.png",:class => "center-block img-responsive carea" %>
    <h2 class="carea_comment">人気９社の中から最適な光回線をお選びいただけます。</h2>

    <div class="search center-block">
        <%= image_tag "pc.png",:class => "center-block" %>
        <div class="text center-block">
          <p>
            お持ちの携帯キャリアや地域などを選ぶだけで最適な光回線を見つけられる、
            ひかりABC「回線診断」。<br>
            ランキング形式で表示されるから見比べることも可能。
          </p>

        </div>
        <div>
          <div class="to_auto center-block">
            <a href="<%= autoSelection_path %>">
              <button class="btn btn_to_auto">
                <h3 class="btn_to_auto_text"><i class="glyphicon glyphicon-circle-arrow-right"></i>回線診断へ</h3>
              </button>
            </a>
          </div>
        </div>
    </div>

    <div class="row">
      <div class="about-content col-sm-4 col-xs-12 center-block">
        <h3 class="text-success text-center">step.<span class="big">A</span></h3>
        <div class="text-a abc">
          <p>まずは光回線について徹底解説。
            データ通信量の多いこの時代・・・<br>
            使い放題の光回線は必須ですね。
            プロバイダーやキャッシュバックが
            なぜもらえるのかなど、
            分かりやすく解説していきます。
          </p>
        </div>
      </div>
      <div class="about-content col-sm-4 col-xs-12 center-block">
        <h3 class="text-info text-center">step.<span class="big">B</span></h3>
        <div class="text-b abc">
          <p>
            いろいろ調べるのは面倒・・・<br>
            そんな方にもおすすめ。
            お持ちの携帯電話、ご契約中の光回線などを入力するだけで、最適なインターネット回線を診断できます。<br>
            提案された回線だけをチェックすれば簡単に回線をお選びいただけます。
          </p>
        </div>

      </div>
      <div class="about-content col-sm-4 col-xs-12 center-block">
        <h3 class="text-warning text-center">step.<span class="big">C</span></h3>
        <div class="text-c abc">
          <p>
            回線を選んだらあとは契約。
            キャッシュバックが多いなど、条件の良い代理店が、回線案内ページに表示されています。
            細かい料金や解約時の違約金なども代理店で聞けるので代理店ページへ進みましょう。
          </p>
        </div>
      </div>
    </div>
    <h3 class="btn-contents">コンテンツ</h1>
    <div class="row about-contents">
      <div class="about-content col-sm-4 col-xs-12">
        <a href="<%= about_path %>">
          <div class="about_btn btn-a">
            <button class="btn btn-success">
              <div class="btn_text">
                <h3>そもそも光回線って？</h3>
                <ul>
                  <li>・光回線とは</li>
                  <li>・プロバイダーとは</li>
                  <li>・なぜキャッシュバックがもらえる？</li>
                </ul>
              </div>
            </button>
        </div>
        </a>
      </div>
      <div class="about-content col-sm-4 col-xs-12">
        <a href="<%= select_path %>">
          <div class="about_btn btn-b">
            <button class="btn btn-info">
              <div class="btn_text">
                <h3>回線を選ぶ</h3>
                <ul>
                  <li>・光コラボレーションとは</li>
                  <li>・回線診断</li>
                </ul>
              </div>
            </button>
          </div>
        </a>
      </div>
      <div class="about-content col-sm-4 col-xs-12">
        <a href="<%= all_path %>">
          <div class="about_btn btn-c">
            <button class="btn btn-warning">
              <div class="btn_text">
                <h3>光回線一覧</h3>
                <ul>
                  <li>・光回線一覧</li>
                </ul>
              </div>
            </button>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_advertisement.html.erb
<div class="ad">
  <a href="https://px.a8.net/svt/ejp?a8mat=2NVCPU+6CMH2Q+34XU+66H9D" target="_blank">
<img border="0" width="250" height="250" alt="" src="https://www27.a8.net/svt/bgt?aid=161026338384&wid=001&eno=01&mid=s00000014637001038000&mc=1"></a>
<img border="0" width="1" height="1" src="https://www15.a8.net/0.gif?a8mat=2NVCPU+6CMH2Q+34XU+66H9D" alt="">
<a href="https://px.a8.net/svt/ejp?a8mat=2NVGMP+FK8X0Y+2CPQ+6BEQ9" target="_blank">
<img border="0" width="250" height="250" alt="" src="https://www21.a8.net/svt/bgt?aid=161031409941&wid=001&eno=01&mid=s00000010979001061000&mc=1"></a>
<img border="0" width="1" height="1" src="https://www10.a8.net/0.gif?a8mat=2NVGMP+FK8X0Y+2CPQ+6BEQ9" alt="">
<a href="https://px.a8.net/svt/ejp?a8mat=2NVFUW+AJUKQA+2XB4+C465T" target="_blank">
<img border="0" width="250" height="250" alt="" src="https://www26.a8.net/svt/bgt?aid=161030408638&wid=001&eno=01&mid=s00000013648002035000&mc=1"></a>
<img border="0" width="1" height="1" src="https://www12.a8.net/0.gif?a8mat=2NVFUW+AJUKQA+2XB4+C465T" alt="">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ひかりABC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true, type: 'text/css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61980725-2', 'auto');
  ga('send', 'pageview');

  </script>

</head>
<body>
    <header>
      <nav class="navbar-hikari navbar-default navbar-fixed-top">
        <div class="navbar-header">
          <a href="#menu-toggle" class="btn btn-slide" id="menu-toggle"><i class="glyphicon glyphicon glyphicon-th-list"></i></a>
          <%= link_to "ひかりABC",root_path , class: :top_logo %>
        </div>
      </nav>
    </header>
    <!-- /#sidebar-wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <li class="sidebar-brand">
                <%= link_to(content_tag(:i, '　トップ', class: 'glyphicon glyphicon-home') , root_path) %>
              </li>
              <li>
                <%= link_to "そもそも光回線って？", about_path %>
                <ul>
                  <li><%= link_to "光回線とは", about_path %></li>
                  <li><%= link_to "プロバイダーとは", provider_path %></li>
                  <li><%= link_to "なぜキャッシュバックがもらえる？", cashback_path %></li>
                </ul>
              </li>
              <li>
                  <%= link_to "回線を選ぶ", select_path %>
                  <ul>
                    <li><%= link_to "光コラボレーションとは", select_path %></li>
                    <li><%= link_to "回線診断", autoSelection_path %>
                  </ul>
              </li>
              <li>
                  <span><%= link_to "光回線一覧", all_path %></span>
                  <ul>
                    <li><%= link_to "ドコモ光", docomo_path %></li>
                    <li><%= link_to "SoftBank光", softbank_path %></li>
                    <li><%= link_to "auひかり", au_path %></li>
                    <li><%= link_to "NURO光", nuro_path %></li>
                    <li><%= link_to "コミュファ光", commufa_path %></li>
                    <li><%= link_to "So-net光", sonet_path %></li>
                    <li><%= link_to "OCN光", ocn_path %></li>
                    <li><%= link_to "BIGLOBE光", biglobe_path %></li>
                    <li><%= link_to "U-NEXT光", unext_path %></li>
                  </ul>
              </li>
          </ul>
      </div>
      <!-- Page Content -->
      <div id="page-content-wrapper">

        <%= yield %>
        <footer class="footer">
          <div class="container">
            <p class="text-muted text-center">© 2017 Tetsu Uemura. All Rights Reserved.</p>
          </div>
        </footer>
      </div>
      <!-- /#page-content-wrapper -->


    </div>


    <!-- /#wrapper -->
    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

  </body>
</html>

app/views/select/_auTable.html.erb
<table class="table table-bordered text-center">
  <tr><th>auひかり</th><th>マンション</th><th>戸建</th></tr>
  <tr><td>ギガ得(2年契約)</td><td>3800円*/月</td><td>5200円/月</td></tr>
  <tr><td>ずっとギガ得(3年契約)</td><td>-</td><td>5100円*/月</td></tr>
  <tr><td>光電話</td><td colspan="2">500円/月</td></tr>
  <tr><td>光テレビ</td><td colspan="2">500円/月</td></tr>
  <tr><td>プロバイダー</td><td colspan="2">@nifty、@TCOM、BIGLOBE、So-net、au one net　など</td></tr>
  <tr><td>セット割</td><td colspan="2">au</td></tr>
</table>
<p>*マンションタイプの料金はお住いのマンション、アパートによって変わります。<br>
  また、契約年数はなく違約金や解約料は発生しませんが、始めの2年以内に解約すると
  別途で初期費用が発生します。<br>
  *ずっとギガ得プランの料金は初年5100円/月、2年目5000円/月、3年目以降4900円/月となります。<br>
</p>

app/views/select/_biglobeTable.html.erb
<table class="table table-bordered text-center">
  <tr><th>BIGLOBE光</th><th>マンション</th><th>戸建</th></tr>
  <tr><td>料金</td><td>4080円/月</td><td>5180円/月</td></tr>
  <tr><td>光電話</td><td colspan="2">500円/月</td></tr>
  <tr><td>光テレビ</td><td colspan="2">660円/月</td></tr>
  <tr><td>プロバイダー</td><td colspan="2">BIGLOBE</td></tr>
  <tr><td>セット割</td><td colspan="2">BIGLOBE(SIM)</td></tr>
</table>

app/views/select/_commufaTable.html.erb
<table class="table table-bordered text-center">
  <tr><th>So-net コミュファ光*</th><th>マンション</th><th>戸建</th></tr>
  <tr><td>料金(30Mbps)</td><td>-</td><td>3808円/月</td></tr>
  <tr><td>料金(100Mbps)</td><td>3880円/月</td><td>-</td></tr>
  <tr><td>料金(300Mbps)</td><td>4600円/月</td><td>4600円/月</td></tr>
  <tr><td>料金(1Gbps)</td><td>5130円/月</td><td>5130円/月</td></tr>
  <tr><td>光電話</td><td colspan="2">300円/月</td></tr>
  <tr><td>光テレビ</td><td colspan="2">460円/月</td></tr>
  <tr><td>プロバイダー</td><td colspan="2">So-net</td></tr>
  <tr><td>セット割</td><td colspan="2">au</td></tr>
</table>
<p>
*提供エリアが中部地方に限られます。<br>
*料金はSo-netのプロバイダ基本料金とコミュファ光プロバイダセレクトタイプを合わせた金額になります。
</p>

app/views/select/_docomoTable.html.erb
<table class="table table-bordered text-center">
  <tr><th>ドコモ光</th><th>マンション</th><th>戸建</th></tr>
  <tr><td>料金A*</td><td>4000円/月</td><td>5200円/月</td></tr>
  <tr><td>料金B*</td><td>4200円/月</td><td>5400円/月</td></tr>
  <tr><td>光電話</td><td colspan="2">500円/月</td></tr>
  <tr><td>光テレビ</td><td colspan="2">660円/月</td></tr>
  <tr><td>プロバイダー</td><td colspan="2">plala、so-net、BIGLOBE、@nifty、@TCOM、OCN など</td></tr>
  <tr><td>セット割</td><td colspan="2">ドコモ</td></tr>
</table>
<p>*ご利用するプロバイダによってAタイプ、Bタイプに分かれます。</p>

app/views/select/autoSelection.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="about_texts auto_form aboutAndProvide">
      <h1> 回線診断</h1>
      <%= form_tag result_path do%>
      <div class="formBlock">
        <div class="about_text">
          <div class="row">
            <h3>ご家族の携帯電話の台数を選択してください。</h3>
              <div class="col-lg-2 col-xs-6">
                <%= label_tag(:docomo, "ドコモ") %>
                <%= select_tag(:numberOfDocomo, options_for_select([0,1,2,3,4,5,6]), class: "form-control") %>
              </div>
              <div class="col-lg-2 col-xs-6">
                <%= label_tag(:softbank, "SoftBank") %>
                <%= select_tag(:numberOfSoftBank, options_for_select([0,1,2,3,4,5,6]), class: "form-control") %>
              </div>
              <div class="col-lg-2 col-xs-6">
                <%= label_tag(:au, "au") %>
                <%= select_tag(:numberOfAu, options_for_select([0,1,2,3,4,5,6]), class: "form-control") %>
              </div>
              <div class="col-lg-2 col-xs-6">
                <%= label_tag(:ymobile, "Y!mobile") %>
                <%= select_tag(:numberOfYmobile, options_for_select([0,1,2,3,4,5,6]), class: "form-control") %>
              </div>
              <div class="col-lg-2 col-xs-6">
                <%= label_tag(:sim, "SIMフリー") %>
                <%= select_tag(:numberOfSIM, options_for_select([0,1,2,3,4,5,6]), class: "form-control") %>
              </div>
          </div>
        </div>
      </div>
      <div class="formBlock">
        <div class="about_text">
          <div class="row">
            <h3>現在のご自宅のネット環境について入力してください。</h3>
            <div class="col-xs-6">
              <%= label_tag(:flets, "フレッツ光") %>
              <%= select_tag(:fletsOrNot, options_for_select(["加入なし","加入中"]), class: "form-control") %>
            </div>
            <div class="col-xs-6">
              <%= label_tag(:provider, "プロバイダー") %>
              <%= select_tag(:provider, options_for_select(@provider), class: "form-control") %>
            </div>
          </div>
        </div>
      </div>
      <div class="formBlock">
        <div class="about_text">
          <div class="row">
            <h3>ご希望のオプションについて入力してください。</h3>
            <div class="col-xs-6">
              <%= label_tag(:tel, "固定電話") %>
              <%= select_tag(:telOrNot, options_for_select(["利用する","利用しない"]), class: "form-control") %>
            </div>
            <div class="col-xs-6">
              <%= label_tag(:tv, "ひかりテレビ") %>
              <%= select_tag(:tvOrNot, options_for_select(["利用しない","利用する"]), class: "form-control") %>
            </div>
          </div>
        </div>
      </div>
      <div class="formBlock">
        <div class="about_text">
          <div class="row">
            <h3>ご自宅について入力してください。</h3>
              <div class="col-xs-6">
                <%= label_tag(:type, "タイプ") %>
                <%= select_tag(:type, options_for_select(["戸建タイプ","マンションタイプ"]), class: "form-control") %>
              </div>
              <div class="col-xs-6">
                <%= label_tag(:area, "お住いの地域") %>
                <%= select_tag(:area, options_for_select(["関東","中部","その他"]), class: "form-control") %>
              </div>
            </div>
          </div>
        </div>
        <div class="form_btn">
          <%= submit_tag "診断" , class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>
</div>